apiVersion: v1
kind: ReplicationController
metadata:
  name: golang-server
spec:
  replicas: 1
  selector:
    app: app-server
    component: golang-server
  template:
    metadata:
      name: golang-server
      labels:
        app: app-server
        component: golang-server
    spec:
      containers:
        - name: golang-server
          image: "us.gcr.io/sonic-trail-154010/edu-golang-server:%dockerImageVersion%"
          ports:
            - name: server-port
              containerPort: 4000

---

apiVersion: v1
kind: Service
metadata:
  name: golang-server-svc
  labels:
    app: app-server
    component: golang-server
spec:
  type: ClusterIP
  selector:
    app: app-server
    component: golang-server
  ports:
    - port: 4000
      protocol: TCP
      name: server-port
