apiVersion: v1
kind: ReplicationController
metadata:
  name: lb
spec:
  replicas: 1
  selector:
    app: app-server
    component: lb
  template:
    metadata:
      name: lb
      labels:
        app: app-server
        component: lb
    spec:
      containers:
        - name: lb
          image: "us.gcr.io/sonic-trail-154010/edu-lb:%dockerImageVersion%"
          ports:
            - name: server-port
              containerPort: 80
              hostPort: 80
      